name: Release

on: 
  release:
    types: ["created"]

jobs:
  build_debian:
    runs-on: ubuntu-latest
    steps:
    - name: install dep
      run: sudo apt update && sudo apt install -y wget
    - uses: actions/checkout@v3


    - name: Build
      run: ./build.sh ${{  github.ref_name }}

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'out/*.deb'
